<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useDebounceFn } from '@vueuse/core';
import type { PostBlockItem } from '../editor-tools/PostsBlock';

interface PostSearchResult {
    id: number;
    uuid: string;
    title: string;
    slug: string;
    excerpt?: string;
    image?: string;
    category?: string;
    postType: string;
    publishedAt?: string;
    author?: {
        id: number;
        name: string;
    };
    featured_tag?: {
        id: number;
        name: string;
        slug: string;
    };
}

const props = defineProps<{
    open: boolean;
    excludedPostIds?: number[];
}>();

const emit = defineEmits<{
    'update:open': [value: boolean];
    select: [posts: PostBlockItem[]];
}>();

const isOpen = computed({
    get: () => props.open,
    set: (value) => emit('update:open', value),
});

const searchQuery = ref('');
const isLoading = ref(false);
const posts = ref<PostSearchResult[]>([]);
const selectedPosts = ref<PostSearchResult[]>([]);
const error = ref<string | null>(null);

// Check if a post is excluded (already in block)
function isPostExcluded(postId: number): boolean {
    return props.excludedPostIds?.includes(postId) ?? false;
}

// Check if a post is selected
function isPostSelected(postId: number): boolean {
    return selectedPosts.value.some(p => p.id === postId);
}

// Toggle post selection
function togglePostSelection(post: PostSearchResult) {
    if (isPostExcluded(post.id)) return;

    const index = selectedPosts.value.findIndex(p => p.id === post.id);
    if (index === -1) {
        selectedPosts.value.push(post);
    } else {
        selectedPosts.value.splice(index, 1);
    }
}

// Debounced search
const debouncedSearch = useDebounceFn(async () => {
    await searchPosts();
}, 300);

watch(searchQuery, () => {
    debouncedSearch();
});

// Load initial posts when modal opens
watch(() => props.open, async (open) => {
    if (open) {
        searchQuery.value = '';
        selectedPosts.value = [];
        await searchPosts();
    }
});

async function searchPosts() {
    isLoading.value = true;
    error.value = null;

    try {
        const params = new URLSearchParams();
        if (searchQuery.value) {
            params.set('query', searchQuery.value);
        }
        params.set('limit', '20');

        const response = await fetch(`/cms/layouts/homepage/search-posts?${params.toString()}`);

        if (!response.ok) {
            throw new Error('Failed to fetch posts');
        }

        const data = await response.json();
        posts.value = data.posts;
    } catch (e) {
        error.value = 'Failed to load posts. Please try again.';
        console.error('Post search error:', e);
    } finally {
        isLoading.value = false;
    }
}

// Confirm selection
function confirmSelection() {
    if (selectedPosts.value.length === 0) return;

    // Convert to PostBlockItem format
    // Note: We only store the post ID - the blade component will fetch full data
    const blockItems: PostBlockItem[] = selectedPosts.value.map(post => ({
        id: post.id,
        uuid: '', // Will be fetched by blade component
        title: post.title,
        slug: '', // Will be fetched by blade component
        excerpt: post.excerpt || null,
        featured_image_url: post.image || null,
        featured_image_thumb: post.image || null,
        url: '', // Will be generated by blade component
        author: null, // Will be fetched by blade component
        featured_tag: null, // Will be fetched by blade component
        published_at: post.publishedAt || null,
    }));

    emit('select', blockItems);
    isOpen.value = false;
}
</script>

<template>
    <UModal v-model:open="isOpen" :ui="{ width: 'max-w-2xl' }">
        <template #content>
            <UCard :ui="{ body: 'p-0' }">
                <!-- Header -->
                <div class="flex items-center justify-between p-4 border-b border-default">
                    <div>
                        <h3 class="text-lg font-semibold text-highlighted">Select Posts</h3>
                        <p class="text-sm text-muted mt-1">Search and select posts to embed in your content.</p>
                    </div>
                    <UButton
                        icon="i-lucide-x"
                        color="neutral"
                        variant="ghost"
                        size="sm"
                        @click="isOpen = false"
                    />
                </div>

                <!-- Search -->
                <div class="p-4 border-b border-default">
                    <UInput
                        v-model="searchQuery"
                        placeholder="Search posts..."
                        icon="i-lucide-search"
                        class="w-full"
                        autofocus
                    />
                </div>

                <!-- Selected count -->
                <div v-if="selectedPosts.length > 0" class="px-4 py-2 bg-primary-50 dark:bg-primary-900/20 border-b border-default flex items-center justify-between">
                    <span class="text-sm text-primary-700 dark:text-primary-300">
                        {{ selectedPosts.length }} post{{ selectedPosts.length > 1 ? 's' : '' }} selected
                    </span>
                    <UButton
                        size="xs"
                        variant="ghost"
                        color="primary"
                        @click="selectedPosts = []"
                    >
                        Clear selection
                    </UButton>
                </div>

                <!-- Results -->
                <div class="max-h-[400px] overflow-y-auto">
                    <!-- Loading -->
                    <div v-if="isLoading" class="p-8 text-center">
                        <UIcon name="i-lucide-loader-2" class="size-8 text-muted animate-spin" />
                        <p class="text-sm text-muted mt-2">Loading posts...</p>
                    </div>

                    <!-- Error -->
                    <div v-else-if="error" class="p-8 text-center">
                        <UIcon name="i-lucide-alert-circle" class="size-8 text-error" />
                        <p class="text-sm text-error mt-2">{{ error }}</p>
                        <UButton
                            color="neutral"
                            variant="soft"
                            size="sm"
                            class="mt-4"
                            @click="searchPosts"
                        >
                            Try Again
                        </UButton>
                    </div>

                    <!-- Empty -->
                    <div v-else-if="posts.length === 0" class="p-8 text-center">
                        <UIcon name="i-lucide-file-search" class="size-8 text-muted" />
                        <p class="text-sm text-muted mt-2">No posts found</p>
                    </div>

                    <!-- Posts List -->
                    <div v-else class="divide-y divide-default">
                        <div
                            v-for="post in posts"
                            :key="post.id"
                            :class="[
                                'w-full flex items-center gap-4 p-4 text-left',
                                isPostExcluded(post.id)
                                    ? 'opacity-50 cursor-not-allowed bg-muted/20'
                                    : isPostSelected(post.id)
                                        ? 'bg-primary-50 dark:bg-primary-900/20 cursor-pointer'
                                        : 'hover:bg-muted/50 transition-colors cursor-pointer'
                            ]"
                            @click="togglePostSelection(post)"
                        >
                            <!-- Checkbox -->
                            <div class="shrink-0">
                                <UCheckbox
                                    :model-value="isPostSelected(post.id)"
                                    :disabled="isPostExcluded(post.id)"
                                    @click.stop
                                    @update:model-value="togglePostSelection(post)"
                                />
                            </div>

                            <!-- Image -->
                            <img
                                v-if="post.image"
                                :src="post.image"
                                :alt="post.title"
                                class="size-14 rounded-lg object-cover shrink-0"
                            />
                            <div v-else class="size-14 rounded-lg bg-muted/50 flex items-center justify-center shrink-0">
                                <UIcon name="i-lucide-image" class="size-5 text-muted" />
                            </div>

                            <!-- Content -->
                            <div class="flex-1 min-w-0">
                                <div class="flex items-center gap-2">
                                    <h4 class="font-medium text-highlighted truncate">{{ post.title }}</h4>
                                    <UBadge v-if="isPostExcluded(post.id)" color="warning" variant="subtle" size="xs">
                                        Already added
                                    </UBadge>
                                </div>
                                <p v-if="post.excerpt" class="text-sm text-muted line-clamp-1 mt-0.5">
                                    {{ post.excerpt }}
                                </p>
                                <div class="flex items-center gap-2 mt-1">
                                    <UBadge v-if="post.category" color="neutral" variant="subtle" size="xs">
                                        {{ post.category }}
                                    </UBadge>
                                    <span v-if="post.publishedAt" class="text-xs text-muted">
                                        {{ post.publishedAt }}
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Footer -->
                <div class="flex items-center justify-end gap-3 p-4 border-t border-default">
                    <UButton
                        color="neutral"
                        variant="ghost"
                        @click="isOpen = false"
                    >
                        Cancel
                    </UButton>
                    <UButton
                        color="primary"
                        :disabled="selectedPosts.length === 0"
                        @click="confirmSelection"
                    >
                        Add {{ selectedPosts.length || '' }} Post{{ selectedPosts.length !== 1 ? 's' : '' }}
                    </UButton>
                </div>
            </UCard>
        </template>
    </UModal>
</template>
